In [71]:
import numpy as np
import matplotlib.pyplot as plt

from src.include.font import font
from src.utils import hexa_to_bin_array, add_noise
from src.plots import plot_letters_patterns, plot_letters_patterns_with_noise


In [72]:
char_example = np.copy(font[1])
char_example.resize(7, 1)
print(char_example)

[[ 0]
 [14]
 [ 1]
 [13]
 [19]
 [19]
 [13]]


In [73]:
bin_array = np.zeros(5, dtype=int)
for i in range(0,5):
    bin_array[4-i] = char_example[0] & 1
    char_example[0] >>= 1
bin_array.resize(1, 5)


In [74]:
only_first_row      = np.zeros((7, 5), dtype=int)
only_first_row[0]   = bin_array * 4
only_first_row[1:]  = np.ones((6, 5)) * 3

In [75]:
print(hexa_to_bin_array(font[1]))

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 1]
 [0 1 1 0 1]
 [1 0 0 1 1]
 [1 0 0 1 1]
 [0 1 1 0 1]]


In [76]:
data = []
letters_patterns = []

for letter in font:
    aux = hexa_to_bin_array(letter)
    data.append(np.concatenate(aux))
    letters_patterns.append(aux)

plot_letters_patterns_with_noise(add_noise(data, 10))
plot_letters_patterns(letters_patterns)

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'